export const materialList = {
  value_body: "/mock/material/value_body.png",
  up: [
    "/mock/material/up_1.png",
    "/mock/material/up_2.png",
    "/mock/material/up_3.png",
    "/mock/material/up_4.png",
    "/mock/material/up_5.png",
    "/mock/material/up_6.png",
    "/mock/material/up_7.png",
    "/mock/material/up_8.png",
    "/mock/material/up_9.png",
    "/mock/material/up_10.png",
    "/mock/material/up_11.png",
    "/mock/material/up_12.png",
    "/mock/material/up_13.png",
    "/mock/material/up_14.png",
  ],
  down: [
    "/mock/material/down_1.png",
    "/mock/material/down_2.png",
    "/mock/material/down_3.png",
    "/mock/material/down_4.png",
    "/mock/material/down_5.png",
    "/mock/material/down_6.png",
    "/mock/material/down_7.png",
    "/mock/material/down_8.png",
    "/mock/material/down_9.png",
    "/mock/material/down_10.png",
    "/mock/material/down_11.png",
    "/mock/material/down_12.png",
    "/mock/material/down_13.png",
    "/mock/material/down_14.png",
  ],
};
